### ISSUE TITLE
add-card-modal - formatting needs fixing 

### ISSUE THREAD

**Issue by zimmermanjosh** [VeronicaSteele/se_project_aroundtheus#4]
New place needs updating 
Title - css name needs review 
add refactoring - checks 
and error handling

**Comment by zimmermanjosh** [comment]
added keys git commit -m "updated: novalidate keys and disabled keys - index.html"

**Comment by zimmermanjosh** [comment]
git commit -m "updated: novalidate keys and disabled keys - index.html"

**Comment by zimmermanjosh** [comment]
.modal__input_type_error {
  border-bottom: 1px solid #ff0000;
}
added to modal.css

**Comment by VeronicaSteele** [comment]
checked css for title naming issues
2 id's for description input (lines 95-96) - both are tied into index,js and used there?

**Comment by zimmermanjosh** [comment]
<img width="1918" alt="Screenshot 2023-07-01 at 2 53 31 PM" src="https://github.com/VeronicaSteele/se_project_aroundtheus/assets/48954338/55eb798b-192a-4b69-adc1-c68109107851">
