### ISSUE TITLE
can't close overlays by clicking outside of modal 

### ISSUE THREAD

**Issue by zimmermanjosh** [VeronicaSteele/se_project_aroundtheus#7]
i would suggest something like this ............

function handlePopupClose(evt) {
  if (
    evt.target.classList.contains("modal") ||
    evt.target.classList.contains("modal__close")
  ) {
    closeModal(evt.currentTarget);
  }
}

**Comment by VeronicaSteele** [comment]
Resolved - VS

**Comment by VeronicaSteele** [comment]
Resolved - VS
